/** Seed payload shape — mirrors the College model without Prisma relation fields. */
export type CollegeSeed = {
  name: string;
  slug: string;
  shortName: string;
  location: string;
  state: string;
  fees: number;
  rating: number;
  careers360Rating: number;
  placement: number;
  placementPercentage: number;
  avgPackage: number;
  highestPackage: number;
  logo?: string | null;
  banner?: string | null;
  image?: string | null;
  campusImages?: string[];
  description?: string | null;
  detailedOverview: string;
  admissionProcess: string;
  eligibility: string;
  website?: string | null;
  officialWebsite: string;
  courses: string[];
  acceptedExams: string[];
  examsAccepted: string[];
  cutoffRank?: number | null;
  recruiters?: string[];
  ranking?: number | null;
  nirfRank?: number | null;
  ownershipType: string;
  establishedYear: number;
  accreditation: string;
  featured: boolean;
  facilities?: string[];
  rankings?: string[];
  images?: string[];
  campusSize: string;
  facultyCount: number;
  studentCount: number;
};

